[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path = 'cache_forge'
solc = "0.8.23"

remappings = ["forge-std/=lib/forge-std/src/"]

[rpc_endpoints]
mainnet = "https://rpc.ankr.com/eth"
zkevm = "https://polygon-rpc.com/zkevm"

# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
