name: "Workflow for Feature branches"

on:
  push:
    branches-ignore:
      - main

jobs:
  solidity:
    uses: martelskiy/workflows/.github/workflows/solidity.yml@main
    with:
      working-directory: ./src
