name: "Workflow for Feature branches"

on:
  push:
    branches-ignore:
      - main

jobs:
  solidity:
    uses: martelskiy/workflows/.github/workflows/solidity.yml@main
    permissions:
      actions: read
      contents: read
      security-events: write
    with:
      working-directory: ./src
